[project]
name = "tibame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-storage>=3.10.1",
    "pandas>=3.0.3",
    "pymysql>=1.2.0",
    "selenium>=4.44.0",
]

[tool.uv.workspace]
members = [
    "tibame",
]
